/*
 * Copyright (c) 2004, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (2.0, build R6)
// Generated source version: 2.0

package client.dispatch.wsdl_hello_lit_asyncpoll.server;

import jakarta.jws.WebService;
import jakarta.xml.ws.soap.SOAPFaultException;
import javax.xml.namespace.QName;

@WebService(
    serviceName="Hello_Service",
    endpointInterface="client.dispatch.wsdl_hello_lit_asyncpoll.server.Hello"
)
public class Hello_PortType_Impl implements client.dispatch.wsdl_hello_lit_asyncpoll.server.Hello, java.rmi.Remote {

     private static final ObjectFactory of = new ObjectFactory();

    public client.dispatch.wsdl_hello_lit_asyncpoll.server.HelloResponse hello(client.dispatch.wsdl_hello_lit_asyncpoll.server.Hello_Type parameters) {

        //System.out.println("Hello_PortType_Impl received: " + .getArgument() +
        //    ", " + req.getExtra());
        try{
        HelloResponse resp = of.createHelloResponse();
        resp.setArgument(parameters.getArgument());
        resp.setExtra(parameters.getExtra());
        return resp;
        }catch(Exception e)
        {
         throw new SOAPFaultException(null);
        }

    }

    public client.dispatch.wsdl_hello_lit_asyncpoll.server.HelloResponseException helloException(client.dispatch.wsdl_hello_lit_asyncpoll.server.HelloException parameters)  {

        System.out.println("Hello_PortType_Impl received: " + parameters.getArgument() +
            ", " + parameters.getExtra());

        HelloResponseException resp = of.createHelloResponseException();
        return resp;

    }

    public client.dispatch.wsdl_hello_lit_asyncpoll.server.VoidTestResponse voidTest(client.dispatch.wsdl_hello_lit_asyncpoll.server.VoidTest parameters) {
            return of.createVoidTestResponse();

    }

}
