github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Jakarta XML Web Services]
description: [Eclipse Implementation of XML Web Services]

links:
  source: https://github.com/eclipse-ee4j/metro-jax-ws
  api: https://javadoc.io/doc/jakarta.xml.ws/jakarta.xml.ws-api/2.3.3/overview-summary.html
  spec: https://jakarta.ee/specifications/xml-web-services/
  guide: https://eclipse-ee4j.github.io/metro-jax-ws/2.3.3/docs/
  plugin: https://eclipse-ee4j.github.io/metro-jax-ws/jaxws-maven-plugin/
  javadocsrt:  https://javadoc.io/doc/com.sun.xml.ws/jaxws-rt/2.3.3/com.sun.xml.ws/module-summary.html
  javadocstools:  https://javadoc.io/doc/com.sun.xml.ws/jaxws-tools/2.3.3/com.sun.xml.ws/module-summary.html
  download: https://repo1.maven.org/maven2/com/sun/xml/ws/jaxws-ri/2.3.3/jaxws-ri-2.3.3.zip
  mailinglist: https://accounts.eclipse.org/mailing-list/metro-dev