github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Jakarta XML Web Services]
description: [Eclipse Implementation of XML Web Services]

links:
  source: https://github.com/eclipse-ee4j/metro-jax-ws
  api: https://javadoc.io/doc/jakarta.xml.ws/jakarta.xml.ws-api/4.0.0/
  spec: https://jakarta.ee/specifications/xml-web-services/
  guide: https://eclipse-ee4j.github.io/metro-jax-ws/4.0.0/docs/
  plugin: https://eclipse-ee4j.github.io/metro-jax-ws/jaxws-maven-plugin/
  javadocsrt:  https://javadoc.io/doc/com.sun.xml.ws/jaxws-rt/4.0.0/
  javadocstools:  https://javadoc.io/doc/com.sun.xml.ws/jaxws-tools/4.0.0/
  download: https://repo1.maven.org/maven2/com/sun/xml/ws/jaxws-ri/4.0.0/jaxws-ri-4.0.0.zip
  mailinglist: https://accounts.eclipse.org/mailing-list/metro-dev