<?xml version="1.0"  encoding="ISO-8859-1" ?>
<!--

    Copyright (c) 2018, 2019 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Distribution License v. 1.0, which is available at
    http://www.eclipse.org/org/documents/edl-v10.php.

    SPDX-License-Identifier: BSD-3-Clause

-->

 <!DOCTYPE definitions
  [
  <!ELEMENT foo ANY >
 <!ELEMENT foo2 ANY >
 <!ENTITY p1 SYSTEM "file:///shihguo/xxxxxxxxxxxxxx">
 <!ENTITY p2 SYSTEM "<!ENTITY e1 SYSTEM &p1; >">
  ]>
 <definitions xmlns="http://schemas.xmlsoap.org/wsdl/">
 <foo2> sample1 </foo2>
 <foo>&p1;</foo>
 </definitions>
