/*
 * Copyright (c) 2004, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Hello_Impl.java
 *
 * Created on July 25, 2003, 10:37 AM
 */

package client.dispatch.null_jaxb.server;

import client.dispatch.null_jaxb.server.HelloResponse;
import client.dispatch.null_jaxb.server.HelloRequest;
import client.dispatch.null_jaxb.server.HelloOneWayRequest;

import jakarta.jws.WebParam;
import java.util.List;


/**
 * Impl class for interface generated by wscompile -import.
 * This class will overwrite the impl class generated by wscompile.
 */

@jakarta.jws.WebService(endpointInterface = "client.dispatch.null_jaxb.server.Hello")

public class Hello_PortType_Impl implements Hello {

    public HelloResponse hello(
           HelloRequest parameters){
           System.out.println("Invoking hello");
           HelloResponse resp = new HelloResponse();
           resp.setArgument("Foo");
        return resp;
    }

     public void helloOneWay(
        HelloOneWayRequest parameters){
         System.out.println("invoking hello oneway");
     }

}
