/*
 * Copyright (c) 2012, 2019 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package com.sun.xml.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocServicePortType", targetNamespace = "http://performance.bea.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocServicePortType {


    /**
     * 
     * @param getRate
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(name = "FloatRateOutput", targetNamespace = "http://weblogic/performance/benchmarks/jwswsee/doc", partName = "FloatRateOutput")
    public float getRate(
        @WebParam(name = "getRate", targetNamespace = "http://performance.bea.com", partName = "getRate")
        String getRate);

}
