/*
 * Copyright (c) 2004, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package client.dispatch.wsdl_hello_lit_asynchandler.server;



import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;

/**
 * Impl class for interface generated by wscompile -import.
 * This class will overwrite the impl class generated by wscompile.
 */
@jakarta.jws.WebService(serviceName="Hello_Service",
endpointInterface="client.dispatch.wsdl_hello_lit_asynchandler.server.Hello")
public class Hello_PortType_Impl implements Hello{
    //private static final ObjectFactory of = new ObjectFactory();

    public HelloOutput hello(Hello_Type req)  {
        System.out.println("Hello_PortType_Impl received: " + req.getArgument() +
            ", " + req.getExtra());
        try{
        HelloOutput resp = new HelloOutput();
        resp.setArgument("Dispatch ");
        resp.setExtra("Test ");
        return resp;
        }catch(Exception e){e.printStackTrace();}
        return null;
    }

    public VoidTestResponse voidTest(VoidTest req) {
        try{
            return new VoidTestResponse();
        }catch(Exception e){e.printStackTrace();}
        return null;
    }

     public HelloOutput helloServerException(Hello_Type req) {
        try{
            return new HelloOutput();
        }catch(Exception e){e.printStackTrace();}
        return null;
    }

}
