/*
 * Copyright (c) 2013, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package whitebox.endpoint.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-02/22/2006 11:22 PM(jitu)-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "RpcLitIF", targetNamespace = "http://echo.abstract.org/", wsdlLocation = "RpcLitEndpoint.wsdl")
@SOAPBinding(style = Style.RPC)
public interface RpcLitEndpointIF {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int echoInteger(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
