/*
 * Copyright (c) 2012, 2019 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package com.sun.xml.ws.sdo.sample.service;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build build (050908.2342.55399))

@WebServiceClient(wsdlLocation =
                  "http://slc05kwl:39901/sdoTest/sdoTest?wsdl",
                  targetNamespace = "http://sdo.sample.service/",
                  name = "HRAppService")
public class HRAppService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.sun.xml.ws.sdo.sample.service.HRAppService_Service");
      URL baseUrl = HRAppService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
          HRAppService_Service.class
          .getResource("http://slc05kwl:39901/sdoTest/sdoTest?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURI().toURL();
          wsdlLocationURL =
            new URL(baseUrl, "http://slc05kwl:39901/sdoTest/sdoTest?wsdl");
        }
      }
      else
      {
        wsdlLocationURL =
          new URL(baseUrl, "http://slc05kwl:39901/sdoTest/sdoTest?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
                 "Failed to create wsdlLocationURL using http://slc05kwl:39901/sdoTest/sdoTest?wsdl",
                 e);
    }
  }

  public HRAppService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://sdo.sample.service/", "HRAppService"));
  }

  public HRAppService_Service(URL wsdlLocation, WebServiceFeature... features) {
      super(wsdlLocation, new QName("http://sdo.sample.service/", "HRAppService"), features);
  }

  public HRAppService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name = "HRAppServiceSoapHttpPort")
  public com.sun.xml.ws.sdo.sample.service.HRAppService getHRAppServiceSoapHttpPort()
  {
    return (com.sun.xml.ws.sdo.sample.service.HRAppService) super.getPort(new QName("http://sdo.sample.service/",
                                                                     "HRAppServiceSoapHttpPort"),
                                                                     com.sun.xml.ws.sdo.sample.service.HRAppService.class);
  }

  @WebEndpoint(name = "HRAppServiceSoapHttpPort")
  public com.sun.xml.ws.sdo.sample.service.HRAppService getHRAppServiceSoapHttpPort(WebServiceFeature... features)
  {
    return (com.sun.xml.ws.sdo.sample.service.HRAppService) super.getPort(new QName("http://sdo.sample.service/",
                                                                     "HRAppServiceSoapHttpPort"),
                                                                     com.sun.xml.ws.sdo.sample.service.HRAppService.class,
                                                           features);
  }
}
