/*
 * Copyright (c) 1997, 2020 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

package fromwsdl.client_from_sei.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-05/14/2009 07:27 PM(jitu)-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Hello", targetNamespace = "urn:test")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
//@XmlSeeAlso({
//    ObjectFactory.class
//})
public interface MyHello {


    /**
     * 
     * @param parameters
     * @return
     *     returns fromwsdl.client_from_sei.server.HelloResponse
     */
    @WebMethod(action = "urn:test:hello")
    @WebResult(name = "HelloResponse", targetNamespace = "urn:test:types", partName = "parameters")
    public MyHelloResponse hello(
        @WebParam(name = "Hello", targetNamespace = "urn:test:types", partName = "parameters")
        MyHello_Type parameters);

}
