/*
 * Copyright (c) 2013, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3010 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.12.15 at 09:10:24 PM PST 
//


package whitebox.message.source.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the whitebox.message.saaj.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Header1_QNAME = new QName("urn:test:types", "Header1");
    private final static QName _Body_QNAME = new QName("urn:test:types", "Body");
    private final static QName _Header2_QNAME = new QName("urn:test:types", "Header2");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: whitebox.message.saaj.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:test:types", name = "Header1")
    public JAXBElement<ValueType> createHeader1(ValueType value) {
        return new JAXBElement<ValueType>(_Header1_QNAME, ValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:test:types", name = "Body")
    public JAXBElement<ValueType> createBody(ValueType value) {
        return new JAXBElement<ValueType>(_Body_QNAME, ValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:test:types", name = "Header2")
    public JAXBElement<ValueType> createHeader2(ValueType value) {
        return new JAXBElement<ValueType>(_Header2_QNAME, ValueType.class, null, value);
    }

}
